"""Template management for medical reports. Built-in + custom templates."""
import json
import os
from sar.fsutil import atomic_write_json

TEMPLATES_PATH = str(__import__("pathlib").Path(__file__).resolve().parent.parent / "data" / "report_templates.json")


def _builtin_templates() -> list[dict]:
    """Pre-loaded report templates shipped with the app."""
    return [
        {
            "id": "tpl_insurance",
            "name": "Insurance Medical Report",
            "category": "insurance",
            "description": "Standard medical report for life/health insurance applications",
            "is_builtin": True,
            "questions": [
                {"id": "ins_q1", "text": "Does the patient have any current medical conditions or diagnoses?",
                 "question_type": "yes_no",
                 "keywords": ["diagnosis", "condition", "problem list", "active problems", "current conditions"],
                 "section_hints": ["active problems", "problem list", "diagnoses"], "order": 1},
                {"id": "ins_q2", "text": "Please list all current medications and dosages.",
                 "question_type": "free_text",
                 "keywords": ["medication", "prescription", "drug", "dose", "dosage", "repeat prescription"],
                 "section_hints": ["medications", "current medication", "repeat prescriptions"], "order": 2},
                {"id": "ins_q3", "text": "Has the patient been referred to or attended hospital in the last 5 years?",
                 "question_type": "yes_no",
                 "keywords": ["referral", "hospital", "admission", "outpatient", "A&E", "emergency", "discharge"],
                 "section_hints": ["referrals", "hospital letters"], "order": 3},
                {"id": "ins_q4", "text": "Does the patient have any history of mental health conditions?",
                 "question_type": "yes_no",
                 "keywords": ["mental health", "anxiety", "depression", "psychiatry", "CMHT", "counselling", "CBT"],
                 "section_hints": ["mental health", "psychiatric"], "order": 4},
                {"id": "ins_q5", "text": "Has the patient had any surgical procedures?",
                 "question_type": "yes_no",
                 "keywords": ["surgery", "operation", "procedure", "surgical", "anaesthetic"],
                 "section_hints": ["surgical history", "operations"], "order": 5},
                {"id": "ins_q6", "text": "Does the patient have a family history of significant medical conditions?",
                 "question_type": "free_text",
                 "keywords": ["family history", "hereditary", "genetic", "father", "mother", "sibling"],
                 "section_hints": ["family history"], "order": 6},
                {"id": "ins_q7", "text": "What is the patient's smoking and alcohol status?",
                 "question_type": "free_text",
                 "keywords": ["smoking", "tobacco", "alcohol", "units", "smoker", "non-smoker", "ex-smoker", "drinking"],
                 "section_hints": ["lifestyle", "smoking status", "alcohol"], "order": 7},
                {"id": "ins_q8", "text": "Are there any ongoing investigations or pending results?",
                 "question_type": "yes_no",
                 "keywords": ["investigation", "pending", "blood test", "scan", "MRI", "CT", "X-ray", "ultrasound", "biopsy"],
                 "section_hints": ["investigations", "results"], "order": 8},
                {"id": "ins_q9", "text": "Has the patient's BMI been recorded? If so, what is the latest value?",
                 "question_type": "free_text",
                 "keywords": ["BMI", "body mass index", "weight", "height", "obesity", "overweight"],
                 "section_hints": ["measurements", "observations"], "order": 9},
                {"id": "ins_q10", "text": "What is the patient's latest recorded blood pressure?",
                 "question_type": "free_text",
                 "keywords": ["blood pressure", "BP", "systolic", "diastolic", "hypertension", "mmHg"],
                 "section_hints": ["observations", "vital signs"], "order": 10},
            ],
        },
        {
            "id": "tpl_uc_fitness",
            "name": "Universal Credit Fitness Assessment",
            "category": "benefits",
            "description": "Medical assessment for UC capability for work / limited capability for work",
            "is_builtin": True,
            "questions": [
                {"id": "uc_q1", "text": "What is the patient's primary diagnosis or condition affecting their ability to work?",
                 "question_type": "free_text",
                 "keywords": ["diagnosis", "condition", "disability", "impairment", "chronic"],
                 "section_hints": ["active problems", "problem list"], "order": 1},
                {"id": "uc_q2", "text": "What treatment is the patient currently receiving?",
                 "question_type": "free_text",
                 "keywords": ["treatment", "therapy", "medication", "physiotherapy", "rehabilitation"],
                 "section_hints": ["current treatment", "management plan"], "order": 2},
                {"id": "uc_q3", "text": "What functional limitations does the patient experience in daily activities?",
                 "question_type": "free_text",
                 "keywords": ["mobility", "walking", "standing", "sitting", "lifting", "concentration", "fatigue", "pain"],
                 "section_hints": ["functional assessment", "daily activities"], "order": 3},
                {"id": "uc_q4", "text": "Is the patient's condition likely to improve, remain stable, or deteriorate?",
                 "question_type": "multiple_choice",
                 "options": ["Likely to improve", "Likely to remain stable", "Likely to deteriorate", "Uncertain"],
                 "keywords": ["prognosis", "outlook", "expected", "deterioration", "improvement", "progressive"],
                 "section_hints": ["prognosis"], "order": 4},
                {"id": "uc_q5", "text": "How long has the patient been affected by this condition?",
                 "question_type": "free_text",
                 "keywords": ["onset", "duration", "since", "diagnosed", "first presented"],
                 "section_hints": ["history"], "order": 5},
                {"id": "uc_q6", "text": "Has the patient been referred to any specialist services?",
                 "question_type": "yes_no",
                 "keywords": ["referral", "specialist", "consultant", "outpatient", "clinic"],
                 "section_hints": ["referrals"], "order": 6},
                {"id": "uc_q7", "text": "Does the patient have any mental health conditions that affect their capability for work?",
                 "question_type": "yes_no",
                 "keywords": ["mental health", "anxiety", "depression", "PTSD", "psychosis", "OCD", "bipolar"],
                 "section_hints": ["mental health"], "order": 7},
                {"id": "uc_q8", "text": "Are there any adaptations or support that might enable the patient to work?",
                 "question_type": "free_text",
                 "keywords": ["adaptation", "support", "reasonable adjustment", "occupational health", "phased return"],
                 "section_hints": ["recommendations"], "order": 8},
            ],
        },
        {
            "id": "tpl_military",
            "name": "Army Medical Report",
            "category": "military",
            "description": "Medical report for military recruitment, fitness assessment, or service records",
            "is_builtin": True,
            "questions": [
                {"id": "mil_q1", "text": "Does the patient have any history of mental health conditions (anxiety, depression, self-harm, eating disorders)?",
                 "question_type": "yes_no",
                 "keywords": ["mental health", "anxiety", "depression", "self-harm", "eating disorder", "psychiatry", "CAMHS", "counselling"],
                 "section_hints": ["mental health", "psychiatric history"], "order": 1},
                {"id": "mil_q2", "text": "Does the patient have any musculoskeletal conditions or history of fractures/joint problems?",
                 "question_type": "yes_no",
                 "keywords": ["fracture", "joint", "knee", "back", "spine", "musculoskeletal", "ligament", "tendon", "dislocation"],
                 "section_hints": ["musculoskeletal", "orthopaedic"], "order": 2},
                {"id": "mil_q3", "text": "Does the patient have any respiratory conditions (asthma, COPD)?",
                 "question_type": "yes_no",
                 "keywords": ["asthma", "inhaler", "COPD", "respiratory", "wheeze", "breathlessness", "peak flow"],
                 "section_hints": ["respiratory"], "order": 3},
                {"id": "mil_q4", "text": "Does the patient have any cardiovascular conditions or abnormal ECGs?",
                 "question_type": "yes_no",
                 "keywords": ["heart", "cardiac", "ECG", "murmur", "palpitations", "chest pain", "hypertension"],
                 "section_hints": ["cardiovascular", "cardiac"], "order": 4},
                {"id": "mil_q5", "text": "Does the patient have any history of seizures or epilepsy?",
                 "question_type": "yes_no",
                 "keywords": ["seizure", "epilepsy", "fit", "convulsion", "blackout", "loss of consciousness"],
                 "section_hints": ["neurological"], "order": 5},
                {"id": "mil_q6", "text": "What is the patient's current medication list?",
                 "question_type": "free_text",
                 "keywords": ["medication", "prescription", "drug", "dose", "repeat"],
                 "section_hints": ["medications", "repeat prescriptions"], "order": 6},
                {"id": "mil_q7", "text": "Does the patient have any skin conditions (eczema, psoriasis)?",
                 "question_type": "yes_no",
                 "keywords": ["eczema", "psoriasis", "dermatitis", "skin", "rash"],
                 "section_hints": ["dermatology", "skin"], "order": 7},
                {"id": "mil_q8", "text": "Does the patient have any visual or hearing impairments?",
                 "question_type": "yes_no",
                 "keywords": ["vision", "sight", "hearing", "deaf", "glasses", "contact lenses", "audiogram"],
                 "section_hints": ["ophthalmology", "audiology", "ENT"], "order": 8},
                {"id": "mil_q9", "text": "Has the patient had any surgical operations?",
                 "question_type": "yes_no",
                 "keywords": ["surgery", "operation", "procedure", "surgical", "appendectomy", "tonsillectomy"],
                 "section_hints": ["surgical history", "operations"], "order": 9},
                {"id": "mil_q10", "text": "Does the patient have any drug or alcohol history?",
                 "question_type": "yes_no",
                 "keywords": ["drug", "substance", "cannabis", "cocaine", "alcohol", "misuse", "addiction"],
                 "section_hints": ["substance misuse", "alcohol"], "order": 10},
            ],
        },
        {
            "id": "tpl_safeguarding",
            "name": "Safeguarding / MASH Response",
            "category": "safeguarding",
            "description": "Medical information for safeguarding enquiries and Multi-Agency Safeguarding Hub (MASH) requests",
            "is_builtin": True,
            "questions": [
                {"id": "sg_q1", "text": "Is the patient known to the practice? How long have they been registered?",
                 "question_type": "free_text",
                 "keywords": ["registered", "registration", "new patient", "temporary"],
                 "section_hints": ["registration"], "order": 1},
                {"id": "sg_q2", "text": "Does the patient have any known vulnerabilities or safeguarding concerns on record?",
                 "question_type": "yes_no",
                 "keywords": ["safeguarding", "vulnerable", "concern", "at risk", "MARAC", "child protection", "CP plan"],
                 "section_hints": ["safeguarding", "alerts"], "order": 2},
                {"id": "sg_q3", "text": "Are there any mental health diagnoses or concerns?",
                 "question_type": "free_text",
                 "keywords": ["mental health", "anxiety", "depression", "psychosis", "self-harm", "suicidal", "crisis", "sectioned"],
                 "section_hints": ["mental health"], "order": 3},
                {"id": "sg_q4", "text": "Is there any history of substance or alcohol misuse?",
                 "question_type": "yes_no",
                 "keywords": ["substance", "drug", "alcohol", "misuse", "addiction", "dependency", "methadone", "detox"],
                 "section_hints": ["substance misuse", "alcohol"], "order": 4},
                {"id": "sg_q5", "text": "Are there any indicators of domestic abuse or coercive control?",
                 "question_type": "yes_no",
                 "keywords": ["domestic", "abuse", "violence", "coercive", "control", "assault", "injury", "DV", "DASH"],
                 "section_hints": ["domestic abuse", "safeguarding"], "order": 5},
                {"id": "sg_q6", "text": "Has the patient presented with any unexplained injuries or frequent attendances?",
                 "question_type": "yes_no",
                 "keywords": ["injury", "bruise", "fracture", "burn", "unexplained", "frequent", "attendance", "A&E"],
                 "section_hints": ["presentations", "attendances"], "order": 6},
                {"id": "sg_q7", "text": "Are there children in the household? Any concerns about child welfare?",
                 "question_type": "free_text",
                 "keywords": ["child", "children", "minor", "dependant", "welfare", "neglect", "FGM", "CSE"],
                 "section_hints": ["family", "dependants", "child protection"], "order": 7},
                {"id": "sg_q8", "text": "What is the patient's current medication and are they compliant?",
                 "question_type": "free_text",
                 "keywords": ["medication", "prescription", "compliance", "non-compliance", "adherence", "missed appointment", "DNA"],
                 "section_hints": ["medications", "compliance"], "order": 8},
                {"id": "sg_q9", "text": "Has the patient been referred to or is known to any support services?",
                 "question_type": "free_text",
                 "keywords": ["social services", "CAMHS", "health visitor", "social worker", "refuge", "support", "CPN", "CMHT"],
                 "section_hints": ["referrals", "agencies"], "order": 9},
                {"id": "sg_q10", "text": "Are there any other risk factors or relevant information?",
                 "question_type": "free_text",
                 "keywords": ["risk", "concern", "trafficking", "exploitation", "isolation", "homelessness", "county lines"],
                 "section_hints": ["risk factors"], "order": 10},
            ],
        },
        {
            "id": "tpl_pip",
            "name": "DWP PIP Further Evidence (GP Factual Report)",
            "category": "benefits",
            "description": "Factual report for Personal Independence Payment — daily living and mobility evidence requested by DWP / assessment providers",
            "is_builtin": True,
            "questions": [
                {"id": "pip_q1", "text": "What are the patient's diagnoses and how long has each condition been present?",
                 "question_type": "free_text",
                 "keywords": ["diagnosis", "condition", "diagnosed", "onset", "chronic", "since"],
                 "section_hints": ["active problems", "problem list", "history"], "order": 1},
                {"id": "pip_q2", "text": "What treatment and medication is the patient currently receiving?",
                 "question_type": "free_text",
                 "keywords": ["medication", "treatment", "dose", "repeat prescription", "therapy", "physiotherapy", "injection"],
                 "section_hints": ["medications", "current treatment"], "order": 2},
                {"id": "pip_q3", "text": "How is the patient's mobility affected (walking distance, aids used, pain, breathlessness)?",
                 "question_type": "free_text",
                 "keywords": ["mobility", "walking", "walking stick", "crutches", "wheelchair", "frame", "distance", "breathless", "pain on walking", "gait"],
                 "section_hints": ["mobility", "functional assessment"], "order": 3},
                {"id": "pip_q4", "text": "How are daily living activities affected (washing, dressing, preparing food, managing medication, finances)?",
                 "question_type": "free_text",
                 "keywords": ["washing", "dressing", "cooking", "preparing food", "personal care", "ADL", "activities of daily living", "self-care", "carer"],
                 "section_hints": ["daily living", "functional assessment", "social"], "order": 4},
                {"id": "pip_q5", "text": "Does the patient have any cognitive, communication or mental health difficulties affecting daily function?",
                 "question_type": "free_text",
                 "keywords": ["cognitive", "memory", "concentration", "communication", "anxiety", "depression", "panic", "confusion", "dementia"],
                 "section_hints": ["mental health", "cognition"], "order": 5},
                {"id": "pip_q6", "text": "Does the patient use any aids, appliances or adaptations?",
                 "question_type": "free_text",
                 "keywords": ["aid", "appliance", "adaptation", "rail", "commode", "hoist", "stairlift", "hearing aid", "dosette"],
                 "section_hints": ["equipment", "occupational therapy"], "order": 6},
                {"id": "pip_q7", "text": "Is there a history of falls, or risk to the patient when alone (safety awareness, supervision needs)?",
                 "question_type": "yes_no",
                 "keywords": ["fall", "falls", "collapse", "supervision", "safety", "risk", "left alone", "wandering"],
                 "section_hints": ["falls", "risk"], "order": 7},
                {"id": "pip_q8", "text": "Does the condition fluctuate (good days / bad days)? Describe variability.",
                 "question_type": "free_text",
                 "keywords": ["fluctuate", "variable", "flare", "relapse", "remission", "good days", "bad days", "episodic"],
                 "section_hints": ["history", "progress"], "order": 8},
                {"id": "pip_q9", "text": "What is the prognosis? Is the condition likely to improve, remain stable, or deteriorate?",
                 "question_type": "multiple_choice",
                 "options": ["Likely to improve", "Likely to remain stable", "Likely to deteriorate", "Uncertain"],
                 "keywords": ["prognosis", "outlook", "progressive", "deteriorating", "improving", "long-term"],
                 "section_hints": ["prognosis"], "order": 9},
            ],
        },
        {
            "id": "tpl_dvla",
            "name": "DVLA Fitness to Drive (Medical Questionnaire)",
            "category": "dvla",
            "description": "GP factual response to DVLA medical enquiry — based on 'Assessing fitness to drive' domains",
            "is_builtin": True,
            "questions": [
                {"id": "dvla_q1", "text": "Has the patient had any seizures, fits, blackouts or unexplained loss of consciousness? Give dates.",
                 "question_type": "yes_no",
                 "keywords": ["seizure", "epilepsy", "fit", "blackout", "syncope", "loss of consciousness", "collapse", "TIA"],
                 "section_hints": ["neurology"], "order": 1},
                {"id": "dvla_q2", "text": "Does the patient have diabetes? If insulin-treated, is hypoglycaemia awareness intact and are there episodes of severe hypoglycaemia?",
                 "question_type": "free_text",
                 "keywords": ["diabetes", "insulin", "hypoglycaemia", "hypo", "HbA1c", "glucose", "awareness", "DKA"],
                 "section_hints": ["diabetes", "diabetic review"], "order": 2},
                {"id": "dvla_q3", "text": "Is there any cardiac history (MI, arrhythmia, pacemaker/ICD, angina, syncope)?",
                 "question_type": "yes_no",
                 "keywords": ["myocardial infarction", "MI", "arrhythmia", "atrial fibrillation", "pacemaker", "ICD", "angina", "stent", "cardiac", "syncope"],
                 "section_hints": ["cardiology", "cardiovascular"], "order": 3},
                {"id": "dvla_q4", "text": "Does the patient meet visual standards (acuity, visual fields)? Any eye conditions on record?",
                 "question_type": "free_text",
                 "keywords": ["visual acuity", "vision", "visual field", "glaucoma", "cataract", "diplopia", "macular", "ophthalmology"],
                 "section_hints": ["ophthalmology", "vision"], "order": 4},
                {"id": "dvla_q5", "text": "Is there any history of alcohol or drug misuse or dependence? Include dates of last use and any treatment.",
                 "question_type": "yes_no",
                 "keywords": ["alcohol", "dependence", "misuse", "drug", "substance", "detox", "units", "cannabis", "cocaine", "opiate"],
                 "section_hints": ["alcohol", "substance misuse"], "order": 5},
                {"id": "dvla_q6", "text": "Is there any psychiatric condition (psychosis, severe depression, mania) affecting safe driving?",
                 "question_type": "yes_no",
                 "keywords": ["psychosis", "schizophrenia", "bipolar", "mania", "severe depression", "sectioned", "psychiatric admission"],
                 "section_hints": ["mental health", "psychiatry"], "order": 6},
                {"id": "dvla_q7", "text": "Is there any cognitive impairment or dementia? Include cognitive test scores if recorded.",
                 "question_type": "yes_no",
                 "keywords": ["dementia", "cognitive", "memory clinic", "MMSE", "MOCA", "GPCOG", "Alzheimer", "confusion"],
                 "section_hints": ["cognition", "memory"], "order": 7},
                {"id": "dvla_q8", "text": "Is there a diagnosis of sleep apnoea or excessive daytime sleepiness? Is treatment (e.g. CPAP) effective?",
                 "question_type": "yes_no",
                 "keywords": ["sleep apnoea", "OSA", "CPAP", "Epworth", "daytime sleepiness", "snoring", "narcolepsy"],
                 "section_hints": ["sleep", "respiratory"], "order": 8},
                {"id": "dvla_q9", "text": "Is the patient on any medication likely to impair driving (sedatives, opioids, hypnotics)?",
                 "question_type": "free_text",
                 "keywords": ["sedative", "opioid", "morphine", "benzodiazepine", "diazepam", "zopiclone", "drowsiness", "pregabalin", "gabapentin"],
                 "section_hints": ["medications"], "order": 9},
            ],
        },
        {
            "id": "tpl_firearms",
            "name": "Firearms / Shotgun Licence Medical Report",
            "category": "licensing",
            "description": "GP medical information for police firearms licensing (Home Office / BMA framework)",
            "is_builtin": True,
            "questions": [
                {"id": "fa_q1", "text": "Is there any history of depression, anxiety or other mental health conditions? Include dates and treatment.",
                 "question_type": "yes_no",
                 "keywords": ["depression", "anxiety", "mental health", "antidepressant", "low mood", "stress", "counselling", "CBT"],
                 "section_hints": ["mental health"], "order": 1},
                {"id": "fa_q2", "text": "Is there any history of suicidal ideation, suicide attempts or self-harm?",
                 "question_type": "yes_no",
                 "keywords": ["suicide", "suicidal", "self-harm", "overdose", "ideation", "crisis team", "attempted"],
                 "section_hints": ["mental health", "risk"], "order": 2},
                {"id": "fa_q3", "text": "Is there any history of alcohol or drug misuse or dependence?",
                 "question_type": "yes_no",
                 "keywords": ["alcohol", "drug", "substance", "misuse", "dependence", "units", "intoxication", "detox"],
                 "section_hints": ["alcohol", "substance misuse"], "order": 3},
                {"id": "fa_q4", "text": "Is there any evidence of dementia or other cognitive impairment?",
                 "question_type": "yes_no",
                 "keywords": ["dementia", "cognitive", "memory", "MMSE", "confusion", "Alzheimer"],
                 "section_hints": ["cognition"], "order": 4},
                {"id": "fa_q5", "text": "Is there any diagnosis of personality disorder or psychotic illness?",
                 "question_type": "yes_no",
                 "keywords": ["personality disorder", "psychosis", "schizophrenia", "bipolar", "delusion", "paranoid"],
                 "section_hints": ["mental health", "psychiatry"], "order": 5},
                {"id": "fa_q6", "text": "Are there any neurological conditions (e.g. epilepsy) or physical conditions relevant to safe possession of a firearm?",
                 "question_type": "yes_no",
                 "keywords": ["epilepsy", "seizure", "neurological", "tremor", "Parkinson", "stroke", "visual"],
                 "section_hints": ["neurology"], "order": 6},
                {"id": "fa_q7", "text": "Is the patient prescribed any medication that could impair judgement or coordination?",
                 "question_type": "free_text",
                 "keywords": ["sedative", "opioid", "benzodiazepine", "hypnotic", "drowsiness", "medication"],
                 "section_hints": ["medications"], "order": 7},
                {"id": "fa_q8", "text": "Are there any safeguarding concerns, episodes of violence, or domestic abuse markers on the record?",
                 "question_type": "yes_no",
                 "keywords": ["violence", "aggression", "domestic", "abuse", "safeguarding", "MARAC", "assault", "anger"],
                 "section_hints": ["safeguarding", "alerts"], "order": 8},
                {"id": "fa_q9", "text": "Does the GP have any other concern about the patient possessing a firearm?",
                 "question_type": "free_text",
                 "keywords": ["concern", "risk", "firearm", "shotgun", "licence", "police"],
                 "section_hints": ["summary"], "order": 9},
            ],
        },
        {
            "id": "tpl_adoption",
            "name": "Adoption & Fostering Medical (AH2-style)",
            "category": "social",
            "description": "Health assessment summary for prospective adopters / foster carers, for the agency medical adviser",
            "is_builtin": True,
            "questions": [
                {"id": "ad_q1", "text": "Summarise the applicant's significant past and current medical history.",
                 "question_type": "free_text",
                 "keywords": ["history", "diagnosis", "condition", "chronic", "significant"],
                 "section_hints": ["past medical history", "active problems"], "order": 1},
                {"id": "ad_q2", "text": "Is there any history of mental health conditions, including treatment and current state?",
                 "question_type": "yes_no",
                 "keywords": ["mental health", "depression", "anxiety", "antidepressant", "counselling", "psychiatric", "self-harm"],
                 "section_hints": ["mental health"], "order": 2},
                {"id": "ad_q3", "text": "Is there any history of alcohol or substance misuse?",
                 "question_type": "yes_no",
                 "keywords": ["alcohol", "units", "drug", "substance", "misuse", "smoking", "cannabis"],
                 "section_hints": ["alcohol", "substance misuse", "lifestyle"], "order": 3},
                {"id": "ad_q4", "text": "What are the applicant's BMI, blood pressure, smoking status and relevant lifestyle factors?",
                 "question_type": "free_text",
                 "keywords": ["BMI", "blood pressure", "smoking", "smoker", "exercise", "weight", "lifestyle"],
                 "section_hints": ["observations", "lifestyle", "measurements"], "order": 4},
                {"id": "ad_q5", "text": "Are there any conditions that could affect the applicant's capacity to care for a child (energy, mobility, prognosis)?",
                 "question_type": "free_text",
                 "keywords": ["mobility", "fatigue", "capacity", "prognosis", "limitation", "function", "chronic pain"],
                 "section_hints": ["functional assessment", "prognosis"], "order": 5},
                {"id": "ad_q6", "text": "List current medications and any side effects relevant to caring for a child.",
                 "question_type": "free_text",
                 "keywords": ["medication", "repeat prescription", "dose", "side effect", "drowsiness"],
                 "section_hints": ["medications"], "order": 6},
                {"id": "ad_q7", "text": "Is there any relevant family history of hereditary conditions?",
                 "question_type": "free_text",
                 "keywords": ["family history", "hereditary", "genetic", "inherited"],
                 "section_hints": ["family history"], "order": 7},
                {"id": "ad_q8", "text": "Is there anything else on the record relevant to the adoption/fostering assessment (including safeguarding)?",
                 "question_type": "free_text",
                 "keywords": ["safeguarding", "concern", "social services", "relevant", "domestic"],
                 "section_hints": ["safeguarding", "summary"], "order": 8},
            ],
        },
        {
            "id": "tpl_occhealth",
            "name": "Occupational Health / Fitness for Work Report",
            "category": "employment",
            "description": "GP report for employers / occupational health on fitness for work and recommended adjustments",
            "is_builtin": True,
            "questions": [
                {"id": "oh_q1", "text": "What conditions does the patient have that affect their ability to work?",
                 "question_type": "free_text",
                 "keywords": ["condition", "diagnosis", "work", "occupation", "affecting", "impairment"],
                 "section_hints": ["active problems"], "order": 1},
                {"id": "oh_q2", "text": "What is the current treatment plan and expected duration?",
                 "question_type": "free_text",
                 "keywords": ["treatment", "medication", "therapy", "physiotherapy", "referral", "review"],
                 "section_hints": ["current treatment", "management plan"], "order": 2},
                {"id": "oh_q3", "text": "What functional limitations are relevant to the patient's role (lifting, standing, screen work, concentration, driving)?",
                 "question_type": "free_text",
                 "keywords": ["lifting", "standing", "sitting", "concentration", "fatigue", "manual handling", "driving", "screen"],
                 "section_hints": ["functional assessment"], "order": 3},
                {"id": "oh_q4", "text": "What is the pattern of sickness absence attributable to the condition?",
                 "question_type": "free_text",
                 "keywords": ["fit note", "sick note", "MED3", "absence", "off work", "unfit"],
                 "section_hints": ["fit notes", "certificates"], "order": 4},
                {"id": "oh_q5", "text": "Is the patient on medication that could affect alertness or safety-critical work?",
                 "question_type": "yes_no",
                 "keywords": ["sedative", "drowsiness", "opioid", "benzodiazepine", "alertness", "machinery"],
                 "section_hints": ["medications"], "order": 5},
                {"id": "oh_q6", "text": "What workplace adjustments or phased return arrangements would you recommend?",
                 "question_type": "free_text",
                 "keywords": ["adjustment", "phased return", "amended duties", "reduced hours", "reasonable adjustment", "workstation"],
                 "section_hints": ["recommendations"], "order": 6},
                {"id": "oh_q7", "text": "What is the prognosis and the likely timescale for return to full duties?",
                 "question_type": "free_text",
                 "keywords": ["prognosis", "recovery", "return to work", "timescale", "expected", "improve"],
                 "section_hints": ["prognosis"], "order": 7},
                {"id": "oh_q8", "text": "Is the patient likely to be covered by the Equality Act (condition lasting/expected to last 12+ months with substantial impact)?",
                 "question_type": "yes_no",
                 "keywords": ["12 months", "long-term", "substantial", "disability", "chronic", "permanent"],
                 "section_hints": ["history", "prognosis"], "order": 8},
            ],
        },
        {
            "id": "tpl_travel",
            "name": "Travel Insurance Claim (Cancellation / Curtailment)",
            "category": "insurance",
            "description": "GP factual report supporting a travel insurance claim — pre-existing conditions and fitness to travel",
            "is_builtin": True,
            "questions": [
                {"id": "tr_q1", "text": "What condition led to the cancellation/curtailment, and when was it first diagnosed or reported?",
                 "question_type": "free_text",
                 "keywords": ["diagnosis", "diagnosed", "first presented", "onset", "symptoms", "reported"],
                 "section_hints": ["history", "consultations"], "order": 1},
                {"id": "tr_q2", "text": "At the date the trip was booked, was the condition already known? List relevant consultations before that date.",
                 "question_type": "free_text",
                 "keywords": ["consultation", "attended", "review", "appointment", "seen", "presented"],
                 "section_hints": ["consultations", "history"], "order": 2},
                {"id": "tr_q3", "text": "Were there pre-existing conditions at booking, and were they stable (no medication changes, admissions or new referrals)?",
                 "question_type": "free_text",
                 "keywords": ["pre-existing", "stable", "medication change", "admission", "referral", "deterioration"],
                 "section_hints": ["active problems", "medications"], "order": 3},
                {"id": "tr_q4", "text": "Was the patient advised against travel at any point? By whom and when?",
                 "question_type": "yes_no",
                 "keywords": ["advised against", "not fit to travel", "unfit", "travel advice", "fitness to fly"],
                 "section_hints": ["consultations"], "order": 4},
                {"id": "tr_q5", "text": "Were there any hospital admissions, A&E attendances or significant investigations in the relevant period?",
                 "question_type": "yes_no",
                 "keywords": ["admission", "hospital", "A&E", "emergency", "investigation", "scan", "discharge"],
                 "section_hints": ["hospital letters", "admissions"], "order": 5},
                {"id": "tr_q6", "text": "What treatment and medication was the patient receiving at the time of the claim event?",
                 "question_type": "free_text",
                 "keywords": ["medication", "treatment", "prescribed", "dose"],
                 "section_hints": ["medications"], "order": 6},
                {"id": "tr_q7", "text": "In your opinion, was the cancellation medically necessary and unforeseeable at the time of booking?",
                 "question_type": "free_text",
                 "keywords": ["unforeseeable", "necessary", "sudden", "acute", "unexpected"],
                 "section_hints": ["summary"], "order": 7},
            ],
        },
        {
            "id": "tpl_capacity",
            "name": "Mental Capacity / LPA / Court of Protection (COP3-style)",
            "category": "legal",
            "description": "Capacity evidence for lasting power of attorney, deputyship or Court of Protection applications",
            "is_builtin": True,
            "questions": [
                {"id": "cap_q1", "text": "What diagnosis affects the patient's mental capacity (e.g. dementia, brain injury, learning disability)?",
                 "question_type": "free_text",
                 "keywords": ["dementia", "Alzheimer", "brain injury", "learning disability", "stroke", "cognitive", "delirium"],
                 "section_hints": ["active problems", "cognition"], "order": 1},
                {"id": "cap_q2", "text": "What cognitive assessments have been recorded (MMSE, MoCA, GPCOG) and what were the scores and dates?",
                 "question_type": "free_text",
                 "keywords": ["MMSE", "MoCA", "GPCOG", "ACE", "cognitive test", "score", "memory clinic"],
                 "section_hints": ["cognition", "memory clinic"], "order": 2},
                {"id": "cap_q3", "text": "Can the patient understand, retain, weigh information and communicate decisions about their property and finances?",
                 "question_type": "free_text",
                 "keywords": ["capacity", "understand", "retain", "weigh", "communicate", "finances", "property", "decisions"],
                 "section_hints": ["capacity assessment"], "order": 3},
                {"id": "cap_q4", "text": "Can the patient make decisions about their health and welfare?",
                 "question_type": "free_text",
                 "keywords": ["capacity", "welfare", "health decisions", "consent", "best interests"],
                 "section_hints": ["capacity assessment"], "order": 4},
                {"id": "cap_q5", "text": "Does capacity fluctuate? Is the impairment temporary or permanent?",
                 "question_type": "free_text",
                 "keywords": ["fluctuate", "lucid", "temporary", "permanent", "variable", "delirium"],
                 "section_hints": ["cognition", "prognosis"], "order": 5},
                {"id": "cap_q6", "text": "What is the prognosis — is capacity likely to improve or deteriorate?",
                 "question_type": "multiple_choice",
                 "options": ["Likely to improve", "Likely to remain stable", "Likely to deteriorate", "Uncertain"],
                 "keywords": ["prognosis", "progressive", "deteriorate", "improve", "decline"],
                 "section_hints": ["prognosis"], "order": 6},
                {"id": "cap_q7", "text": "How does the patient communicate, and are any aids or support needed for communication?",
                 "question_type": "free_text",
                 "keywords": ["communication", "speech", "hearing", "interpreter", "aphasia", "non-verbal"],
                 "section_hints": ["communication"], "order": 7},
                {"id": "cap_q8", "text": "Is the patient aware of the application, and have they expressed any views?",
                 "question_type": "free_text",
                 "keywords": ["aware", "views", "wishes", "expressed", "attorney", "deputy"],
                 "section_hints": ["consultations"], "order": 8},
            ],
        },
        {
            "id": "tpl_group2_driver",
            "name": "Taxi / HGV / Group 2 Driver Medical (D4-style)",
            "category": "licensing",
            "description": "Medical declaration for Group 2 (bus/lorry) and local-authority taxi driver licensing",
            "is_builtin": True,
            "questions": [
                {"id": "g2_q1", "text": "Does the patient meet the vision standards? Record acuity, visual fields and any eye conditions.",
                 "question_type": "free_text",
                 "keywords": ["visual acuity", "vision", "visual field", "glasses", "glaucoma", "cataract", "diplopia"],
                 "section_hints": ["ophthalmology", "vision"], "order": 1},
                {"id": "g2_q2", "text": "Does the patient have diabetes? Detail treatment, hypoglycaemia history and self-monitoring.",
                 "question_type": "free_text",
                 "keywords": ["diabetes", "insulin", "sulfonylurea", "hypoglycaemia", "monitoring", "HbA1c"],
                 "section_hints": ["diabetes"], "order": 2},
                {"id": "g2_q3", "text": "Is there any cardiac history (MI, angina, arrhythmia, pacemaker, valve disease)? Include exercise tolerance.",
                 "question_type": "yes_no",
                 "keywords": ["cardiac", "MI", "angina", "arrhythmia", "pacemaker", "stent", "exercise test", "ETT", "echo"],
                 "section_hints": ["cardiology", "cardiovascular"], "order": 3},
                {"id": "g2_q4", "text": "Is there any history of seizures, blackouts, stroke or other neurological conditions?",
                 "question_type": "yes_no",
                 "keywords": ["seizure", "epilepsy", "blackout", "stroke", "TIA", "neurological", "syncope"],
                 "section_hints": ["neurology"], "order": 4},
                {"id": "g2_q5", "text": "Is there any psychiatric history (psychosis, severe mood disorder, recent admission)?",
                 "question_type": "yes_no",
                 "keywords": ["psychiatric", "psychosis", "bipolar", "severe depression", "admission", "sectioned"],
                 "section_hints": ["mental health"], "order": 5},
                {"id": "g2_q6", "text": "Is there any history of alcohol or drug misuse or dependence?",
                 "question_type": "yes_no",
                 "keywords": ["alcohol", "drug", "substance", "misuse", "dependence", "units"],
                 "section_hints": ["alcohol", "substance misuse"], "order": 6},
                {"id": "g2_q7", "text": "Is there a diagnosis of sleep apnoea or excessive sleepiness? Is treatment effective and compliant?",
                 "question_type": "yes_no",
                 "keywords": ["sleep apnoea", "OSA", "CPAP", "Epworth", "sleepiness", "compliance"],
                 "section_hints": ["sleep", "respiratory"], "order": 7},
                {"id": "g2_q8", "text": "Is the patient taking medication that could impair safe driving of a Group 2 vehicle?",
                 "question_type": "free_text",
                 "keywords": ["sedative", "opioid", "benzodiazepine", "drowsiness", "medication", "insulin"],
                 "section_hints": ["medications"], "order": 8},
            ],
        },
        {
            "id": "tpl_housing",
            "name": "Housing / Medical Priority Letter",
            "category": "social",
            "description": "Supporting medical information for housing applications, medical priority rehousing and adaptations",
            "is_builtin": True,
            "questions": [
                {"id": "ho_q1", "text": "What medical conditions does the patient have that are affected by their current housing?",
                 "question_type": "free_text",
                 "keywords": ["condition", "diagnosis", "housing", "affected", "exacerbated", "worse"],
                 "section_hints": ["active problems"], "order": 1},
                {"id": "ho_q2", "text": "How is the patient's mobility affected (stairs, access, distance)? Do they use aids?",
                 "question_type": "free_text",
                 "keywords": ["stairs", "mobility", "wheelchair", "frame", "access", "falls", "stairlift"],
                 "section_hints": ["mobility", "functional assessment"], "order": 2},
                {"id": "ho_q3", "text": "Are there respiratory conditions aggravated by damp, mould or overcrowding?",
                 "question_type": "yes_no",
                 "keywords": ["asthma", "COPD", "respiratory", "damp", "mould", "chest infection", "wheeze", "overcrowding"],
                 "section_hints": ["respiratory"], "order": 3},
                {"id": "ho_q4", "text": "Is the patient's mental health affected by their current housing situation?",
                 "question_type": "yes_no",
                 "keywords": ["mental health", "anxiety", "depression", "stress", "isolation", "housing"],
                 "section_hints": ["mental health"], "order": 4},
                {"id": "ho_q5", "text": "Are there falls, safety incidents or A&E attendances linked to the current property?",
                 "question_type": "yes_no",
                 "keywords": ["fall", "fell", "accident", "injury", "A&E", "stairs", "fracture"],
                 "section_hints": ["falls", "attendances"], "order": 5},
                {"id": "ho_q6", "text": "Does the patient have care needs or carers attending the property?",
                 "question_type": "free_text",
                 "keywords": ["carer", "care package", "care needs", "district nurse", "social care", "package of care"],
                 "section_hints": ["social", "care"], "order": 6},
                {"id": "ho_q7", "text": "What housing changes or adaptations would benefit the patient's health?",
                 "question_type": "free_text",
                 "keywords": ["adaptation", "ground floor", "level access", "wet room", "rehousing", "bungalow", "recommendation"],
                 "section_hints": ["recommendations", "occupational therapy"], "order": 7},
            ],
        },
    ]


def get_all_templates() -> list[dict]:
    """Load all templates (builtins + custom)."""
    templates = _builtin_templates()
    if os.path.exists(TEMPLATES_PATH):
        with open(TEMPLATES_PATH) as f:
            custom = json.load(f)
        templates.extend(custom)
    return templates


def get_template(template_id: str) -> dict | None:
    for t in get_all_templates():
        if t["id"] == template_id:
            return t
    return None


def save_custom_template(template: dict) -> None:
    custom = []
    if os.path.exists(TEMPLATES_PATH):
        with open(TEMPLATES_PATH) as f:
            custom = json.load(f)
    custom.append(template)
    atomic_write_json(TEMPLATES_PATH, custom)


def update_custom_template(template_id: str, updates: dict) -> bool:
    if not os.path.exists(TEMPLATES_PATH):
        return False
    with open(TEMPLATES_PATH) as f:
        custom = json.load(f)
    for t in custom:
        if t["id"] == template_id:
            t.update(updates)
            atomic_write_json(TEMPLATES_PATH, custom)
            return True
    return False


def delete_custom_template(template_id: str) -> bool:
    if not os.path.exists(TEMPLATES_PATH):
        return False
    with open(TEMPLATES_PATH) as f:
        custom = json.load(f)
    before = len(custom)
    custom = [t for t in custom if t["id"] != template_id]
    if len(custom) == before:
        return False
    atomic_write_json(TEMPLATES_PATH, custom)
    return True
